debug = true

dbpath = "./data/data.db"

[proof_of_work]
enable = true
difficulty = 22
ttl_seconds = 90
secret_key = "NjTRFeOWWc2x/5qUHmRWN7MzN2+58Dp+hVElh89Tr58="
#secret_key = ""

# Max http request body size for user registration
[rbody_size_limiter.register]
enable = false
max_rbody_bytes = 4096

# Max http request body size for login
[rbody_size_limiter.login]
enable = false
max_rbody_bytes = 4096

# Max accounts per IP
[account_per_ip_limiter]
enable = false
max_accounts = 7

# At most 5 registration attempts per minute per IP
[ip_rate_limiter.register]
enable = false
max_requests = 5
window_ms = 20000

# At most 10 login attempts per minute per IP
[ip_rate_limiter.login]
enable = false
max_requests = 15
window_ms = 10000

# At most 1 profile request/second per IP
[ip_rate_limiter.profile]
enable = false
max_requests = 1
window_ms = 1000

# At most 10 logout attempts per minute per IP
[ip_rate_limiter.logout]
enable = false
max_requests = 10
window_ms = 60000